// Code generated by protoc-gen-go.
// source: complex.proto
// DO NOT EDIT!

/*
Package complexpb is a generated protocol buffer package.

It is generated from these files:
	complex.proto

It has these top-level messages:
	ComplexMessage
	DummyMessage
*/
package complexpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ComplexMessage struct {
	OneDummy      *DummyMessage   `protobuf:"bytes,2,opt,name=one_dummy,json=oneDummy" json:"one_dummy,omitempty"`
	MultipleDummy []*DummyMessage `protobuf:"bytes,3,rep,name=multiple_dummy,json=multipleDummy" json:"multiple_dummy,omitempty"`
}

func (m *ComplexMessage) Reset()                    { *m = ComplexMessage{} }
func (m *ComplexMessage) String() string            { return proto.CompactTextString(m) }
func (*ComplexMessage) ProtoMessage()               {}
func (*ComplexMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ComplexMessage) GetOneDummy() *DummyMessage {
	if m != nil {
		return m.OneDummy
	}
	return nil
}

func (m *ComplexMessage) GetMultipleDummy() []*DummyMessage {
	if m != nil {
		return m.MultipleDummy
	}
	return nil
}

type DummyMessage struct {
	Id   int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *DummyMessage) Reset()                    { *m = DummyMessage{} }
func (m *DummyMessage) String() string            { return proto.CompactTextString(m) }
func (*DummyMessage) ProtoMessage()               {}
func (*DummyMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *DummyMessage) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DummyMessage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*ComplexMessage)(nil), "example.complex.ComplexMessage")
	proto.RegisterType((*DummyMessage)(nil), "example.complex.DummyMessage")
}

func init() { proto.RegisterFile("complex.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 170 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0xce, 0xcf, 0x2d,
	0xc8, 0x49, 0xad, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4f, 0xad, 0x48, 0x04, 0xf1,
	0xf5, 0xa0, 0xc2, 0x4a, 0x93, 0x18, 0xb9, 0xf8, 0x9c, 0x21, 0x6c, 0xdf, 0xd4, 0xe2, 0xe2, 0xc4,
	0xf4, 0x54, 0x21, 0x2b, 0x2e, 0xce, 0xfc, 0xbc, 0xd4, 0xf8, 0x94, 0xd2, 0xdc, 0xdc, 0x4a, 0x09,
	0x26, 0x05, 0x46, 0x0d, 0x6e, 0x23, 0x59, 0x3d, 0x34, 0x7d, 0x7a, 0x2e, 0x20, 0x59, 0xa8, 0x8e,
	0x20, 0x0e, 0xa0, 0x7a, 0xb0, 0x80, 0x90, 0x0b, 0x17, 0x5f, 0x6e, 0x69, 0x4e, 0x49, 0x26, 0x50,
	0x0d, 0xd4, 0x00, 0x66, 0x05, 0x66, 0xc2, 0x06, 0xf0, 0xc2, 0x34, 0x81, 0x45, 0x95, 0x8c, 0xb8,
	0x78, 0x90, 0xa5, 0x85, 0xf8, 0xb8, 0x98, 0x32, 0x53, 0x24, 0x18, 0x81, 0x4e, 0x61, 0x0d, 0x02,
	0xb2, 0x84, 0x84, 0xb8, 0x58, 0xf2, 0x12, 0x73, 0x53, 0xc1, 0x8e, 0xe3, 0x0c, 0x02, 0xb3, 0x9d,
	0xb8, 0xa3, 0x38, 0xa1, 0x46, 0x17, 0x24, 0x25, 0xb1, 0x81, 0x7d, 0x6b, 0x0c, 0x08, 0x00, 0x00,
	0xff, 0xff, 0x42, 0x3e, 0x86, 0xed, 0xfe, 0x00, 0x00, 0x00,
}
